// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: error_code.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from error_code.proto</summary>
public static partial class ErrorCodeReflection {

  #region Descriptor
  /// <summary>File descriptor for error_code.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ErrorCodeReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChBlcnJvcl9jb2RlLnByb3RvKsJGCgpFUlJPUl9DT0RFEhcKE0VSUk9SX0NP",
          "REVfTk9fRVJST1IQABIbChdFUlJPUl9DT0RFX0lOVEVSTkFMX0VSUhABEhUK",
          "EUVSUk9SX0NPREVfUEZfRVJSEAISHgoaRVJST1JfQ09ERV9FUlJfU0VSVkVS",
          "X0RBVEUQAxImCiJFUlJPUl9DT0RFX1BGX0lOVkFMSURfQUNDRVNTX1RPS0VO",
          "EAQSJwojRVJST1JfQ09ERV9QRVJNSVNTSU9OX1ZFUklGWV9GQUlMRUQQBRIe",
          "ChpFUlJPUl9DT0RFX0VSUl9JTExFR0FMX1JFURAGEicKI0VSUk9SX0NPREVf",
          "T1BfRVRfTk9UX0JFTE9OR19UT19ZT1VSEAcSKQolRVJST1JfQ09ERV9QRl9D",
          "SEFSQUNURVJfQ1JFQVRFX0ZBSUxFRBAIEh4KGkVSUk9SX0NPREVfUEZfTE9H",
          "SU5fRkFJTEVEEAkSIgoeRVJST1JfQ09ERV9QRl9BQ0NfTElOS19IQVNDSEFS",
          "EAoSIQodRVJST1JfQ09ERV9QRl9BQ0NfTElOS19GQVVLRUQQCxIoCiRFUlJP",
          "Ul9DT0RFX1BGX0FDQ19JTlZBTElEQUNDT1VOVFRZUEUQDBIfChtFUlJPUl9D",
          "T0RFX1BMQVlFUl9OT1RfRk9VTkQQZRIoCiRFUlJPUl9DT0RFX1BMQVlFUl9O",
          "QU1FX0FMUkVBRFlfRVhJU1QQZhIkCiBFUlJPUl9DT0RFX1BMQVlFUl9OQU1F",
          "X0xFTl9MSU1JVBBnEiMKH0VSUk9SX0NPREVfUExBWUVSX05BTUVfQkFEX1dP",
          "UkQQaBIaChZFUlJPUl9DT0RFX0FVVEhfRkFJTEVEEGkSJAogRVJST1JfQ09E",
          "RV9BQ0NPVU5UX0NSRUFURV9GQUlMRUQQahIhCh1FUlJPUl9DT0RFX1BMQVlF",
          "Ul9OT1RfRk9VTkRfMhBrEiAKHEVSUk9SX0NPREVfQUNDT1VOVF9OT1RfRk9V",
          "TkQQbBIjCh9FUlJPUl9DT0RFX0dBVEVfQUREX1JPTEVfRkFJTEVEEG0SHQoZ",
          "RVJST1JfQ09ERV9JTlZBTElEX0RFVklDRRBuEhkKFUVSUk9SX0NPREVfQ0FO",
          "T1RfQklORBBvEiYKIkVSUk9SX0NPREVfRFVQTElDQVRFX0NSRUFURV9QTEFZ",
          "RVIQcBIoCiRFUlJPUl9DT0RFX0xPR0lOX1dBSVRfTE9HT1VUX1RJTUVPVVQQ",
          "cRIjCh9FUlJPUl9DT0RFX0xPR0lOX1dJVEhfRVJSX1NUQVRFEHISHAoYRVJS",
          "T1JfQ09ERV9OSUxDTElFTlRJTkZPEHMSHwobRVJST1JfQ09ERV9TRVJWRVJf",
          "Tk9UX0ZPVU5EEHQSJAogRVJST1JfQ09ERV9DT05ORUNUX1NFUlZFUl9GQUlM",
          "RUQQdRIeChpFUlJPUl9DT0RFX0RVUExJQ0FURV9MT0dJThB2EiEKHUVSUk9S",
          "X0NPREVfRkFTVExPR0lOU0VDUkVURVJSEHcSGgoWRVJST1JfQ09ERV9GT1JC",
          "SURFRE1TRxB4EiEKHUVSUk9SX0NPREVfUExBWUVSTkFNRV9OT0NIQU5HEHkS",
          "JAogRVJST1JfQ09ERV9QTEFZRVJfTkFNRV9MRU5fU0hPUlQQehIbChZFUlJP",
          "Ul9DT0RFX0VSUl9DSVRZX0lEEOkHEhwKF0VSUk9SX0NPREVfRVJSX0hFUk9f",
          "UklEEOoHEiYKIUVSUk9SX0NPREVfSEVST19JU19JTl9PVEhFUl9UUk9PUBDr",
          "BxIfChpFUlJPUl9DT0RFX1BMQVlFUl9SRVNfTEFDSxDsBxIcChdFUlJPUl9D",
          "T0RFX0VSUl9CVUlMRF9JRBDtBxInCiJFUlJPUl9DT0RFX0JVSUxEX0FMUkVB",
          "RFlfTUFYX0xFVkVMEO4HEiEKHEVSUk9SX0NPREVfRVJSX0JVSUxEX1JFTFlf",
          "T04Q7wcSJQogRVJST1JfQ09ERV9CVUlMRF9BTFJFQURZX1VQR1JBREUQ8AcS",
          "JwoiRVJST1JfQ09ERV9CUkVQT1JUX0FMUkVBRFlfQ09MTEVDVBDxBxIkCh9F",
          "UlJPUl9DT0RFX0ZVTExfQ09MTEVDVF9CUkVQT1JUEPIHEiYKIUVSUk9SX0NP",
          "REVfU0tJTExfQUxSRUFEWV9SRVNFQVJDSBD0BxIiCh1FUlJPUl9DT0RFX1NL",
          "SUxMX0lTX0lOVEVHUklUWRD1BxInCiJFUlJPUl9DT0RFX0hFUk9fQ0FOTk9U",
          "X0xFQVJOX1NLSUxMEPYHEigKI0VSUk9SX0NPREVfSEVST19DQU5OT1RfRk9S",
          "R0VUX1NLSUxMEPcHEh4KGUVSUk9SX0NPREVfRVJSX0JSRVBPUlRfSUQQ+AcS",
          "KQokRVJST1JfQ09ERV9FUlJfSEVST19SRU1BSU5fQVNHTl9MQUNLEPkHEigK",
          "I0VSUk9SX0NPREVfSEVST19BTFJFQURZX01BWF9BRFZTVEFSEPoHEicKIkVS",
          "Uk9SX0NPREVfQ09OU1VNRV9IRVJPX0NBTk5PVF9ERUwQ+wcSLQooRVJST1Jf",
          "Q09ERV9QUk9NT1RFX0NPTlNVTUVfSEVST19OT1RfU0FNRRD8BxIeChlFUlJP",
          "Ul9DT0RFX0hFUk9fSEFTX0FXQUtFEP4HEiwKJ0VSUk9SX0NPREVfUExBWUVS",
          "X0FMUkVBRFlfRklOSVNIX05FV0JJRRCACBIrCiZFUlJPUl9DT0RFX0FXQUtF",
          "X0NPTlNVTUVfU1RBUl9OT1RfU0FNRRCBCBIlCiBFUlJPUl9DT0RFX0NPTlNV",
          "TUVfSEVST19JTl9UUk9PUBCCCBIqCiVFUlJPUl9DT0RFX0hSRU9fQVdBS0Vf",
          "Q09OU1VNRV9DTlRfRVJSEIMIEigKI0VSUk9SX0NPREVfU0tJTExfSU5ERVhf",
          "T1VUX09GX1JBTkdFEIUIEicKIkVSUk9SX0NPREVfU0tJTExfQ0FOTk9UX0JF",
          "X0xFQVJORUQQhggSKQokRVJST1JfQ09ERV9JTkRFWF9BTFJFQURZX0xFQVJO",
          "X1NLSUxMEIcIEhkKFEVSUk9SX0NPREVfUkVQRUFUX0lEEIgIEi0KKEVSUk9S",
          "X0NPREVfSEVST19BTFJFQURZX0xFQVJOX1RISVNfU0tJTEwQiQgSHAoXRVJS",
          "T1JfQ09ERV9FUlJfU0tJTExfSUQQiggSKQokRVJST1JfQ09ERV9IRVJPX0tJ",
          "TkRfTk9UX01BVENIX1NLSUxMEIsIEi8KKkVSUk9SX0NPREVfSEVST19DT05O",
          "T1RfUkVTRUFSQ0hfVEhJU19TS0lMTBCMCBIfChpFUlJPUl9DT0RFX0VSUl9T",
          "S0lMTF9MRVZFTBCNCBIiCh1FUlJPUl9DT0RFX0VSUl9TS0lMTF9FWFBfTEFD",
          "SxCOCBIjCh5FUlJPUl9DT0RFX0hFUk9fQUxSRUFEWV9MT0NLRUQQjwgSJQog",
          "RVJST1JfQ09ERV9IRVJPX0FMUkVBRFlfVU5MT0NLRUQQkAgSJAofRVJST1Jf",
          "Q09ERV9BTExPVF9BU0dOX1ZBTFVFX0VSUhCRCBInCiJFUlJPUl9DT0RFX0hF",
          "Uk9fTEVWRUxfQ0FOTk9UX0FXQUtFEJIIEi4KKUVSUk9SX0NPREVfRklSU1Rf",
          "U0tJTExfTEVWRUxfQ0FOTk9UX0FXQUtFEJMIEiMKHkVSUk9SX0NPREVfUExB",
          "WUVSX0RJQU1PTkRfTEFDSxCUCBIpCiRFUlJPUl9DT0RFX1JFU0VUX0FTR05f",
          "VFlQRV9OT1RfTUFUQ0gQlQgSJAofRVJST1JfQ09ERV9CVUlMRF9JU19OT1Rf",
          "VVBHUkFERRCWCBIlCiBFUlJPUl9DT0RFX0NPTExFQ1RfVEFYRVNfQ05UX01B",
          "WBCXCBInCiJFUlJPUl9DT0RFX1RSQU5TX1JFU19TUkNfREVTVF9TQU1FEJgI",
          "EikKJEVSUk9SX0NPREVfVFJBTlNfUkVTX0NOVF9MRVNTX1RIQU5fMBCZCBIr",
          "CiZFUlJPUl9DT0RFX1BMQVlFUl9IQVZFX05PVF9UUkFOU19CVUlMRBCaCBIm",
          "CiFFUlJPUl9DT0RFX1RSQU5TX1JFU19TUkNfREVTVF9FUlIQmwgSIgodRVJS",
          "T1JfQ09ERV9GVUxMX0NPTExFQ1RfTEFORFMQnAgSJAofRVJST1JfQ09ERV9F",
          "UlJfUExBWUVSX0NPSU5fTEFDSxCdCBIgChtFUlJPUl9DT0RFX1BMQVlFUl9I",
          "RVJPX0ZVTEwQnggSIQocRVJST1JfQ09ERV9QTEFZRVJfU0tJTExfRlVMTBCf",
          "CBIjCh5FUlJPUl9DT0RFX05PVF9DT01QTEVBVEVEX1RBU0sQoAgSGgoVRVJS",
          "T1JfQ09ERV9FUlJfVEFTS0lEEKEIEh4KGUVSUk9SX0NPREVfVEFTS19OT1Rf",
          "RVhJU1QQoggSHwoaRVJST1JfQ09ERV9FUlJfTkVYVF9UQVNLSUQQowgSIgod",
          "RVJST1JfQ09ERV9VTktOT1dOX1RBU0tfUFJJWkUQpAgSHQoYRVJST1JfQ09E",
          "RV9OT19HT09EU19OQU1FEKUIEh0KGEVSUk9SX0NPREVfTEFDS19SRVNPVVJD",
          "RRCmCBIgChtFUlJPUl9DT0RFX0lOVkFMSURfUFVSQ0hBU0UQpwgSHwoaRVJS",
          "T1JfQ09ERV9XUk9OR19NQVJLRVRfSUQQqAgSHQoYRVJST1JfQ09ERV9NQVJL",
          "RVRfTE9DS0VEEKkIEiEKHEVSUk9SX0NPREVfVEFYX1RJTUVfSU5URVJWQUwQ",
          "qggSHgoZRVJST1JfQ09ERV9HT09EU19TT0xEX09VVBCrCBIfChpFUlJPUl9D",
          "T0RFX1RSQURFX1pFUk9fUkFURRCsCBIbChZFUlJPUl9DT0RFX0lOVkFMSURf",
          "UkVTEK0IEhgKE0VSUk9SX0NPREVfU0FNRV9SRVMQrggSKAojRVJST1JfQ09E",
          "RV9NQVhfTUFSS0VUX1JFRlJFU0hfVElNRVMQrwgSJgohRVJST1JfQ09ERV9C",
          "VUlMRF9USUxFX0xFVkVMX0xJTUlUELAIEiwKJ0VSUk9SX0NPREVfUFJPTU9U",
          "RV9DT05TVU1FX0hFUk9fQ05UX0VSUhCxCBIrCiZFUlJPUl9DT0RFX0ZPUkNF",
          "X0NPTExFQ1RfVEFYRVNfQ05UX01BWBCyCBIpCiRFUlJPUl9DT0RFX05PVF9S",
          "RVFVSVJFX0ZPUkNFX0NPTExFQ1QQswgSGgoVRVJST1JfQ09ERV9PUkRFUl9M",
          "QUNLELQIEiIKHUVSUk9SX0NPREVfQVZBVEFSX1dST05HX0lOREVYELUIEiIK",
          "HUVSUk9SX0NPREVfSU5UUk9fV1JPTkdfTEVOR1RIELYIEh4KGUVSUk9SX0NP",
          "REVfSU5UUk9fQkFEX1dPUkQQtwgSHgoZRVJST1JfQ09ERV9FUlJfUFVTSF9F",
          "VkVOVBC4CBInCiJFUlJPUl9DT0RFX0VSUl9HQUNIQV9FUlJfUEFDS0FHRUlE",
          "ELkIEh0KGEVSUk9SX0NPREVfRVJSX0dBQ0hBX0VORBDHCBIfChpFUlJPUl9D",
          "T0RFX01BUktFVF9PTERfREFUQRDICBIlCiBFUlJPUl9DT0RFX1VOSU9OX09Q",
          "X05PX0FVVEhPUklUWRDMCBIoCiNFUlJPUl9DT0RFX1VOSU9OX05BTUVfQUxS",
          "RUFEWV9FWElTVBDNCBIkCh9FUlJPUl9DT0RFX1VOSU9OX05BTUVfTEVOX0xJ",
          "TUlUEM4IEiMKHkVSUk9SX0NPREVfVU5JT05fTkFNRV9CQURfV09SRBDPCBIf",
          "ChpFUlJPUl9DT0RFX1VOSU9OX05PVF9FWElTVBDQCBIjCh5FUlJPUl9DT0RF",
          "X1VOSU9OX0FMUkVBRFlfQVBQTFkQ0QgSHwoaRVJST1JfQ09ERV9VTklPTl9O",
          "T1RfQVBQTFkQ0wgSJgohRVJST1JfQ09ERV9VTklPTl9NRU1CRVJfTk9UX0VY",
          "SVNUENQIEiUKIEVSUk9SX0NPREVfVU5JT05fVElUTEVfTk9UX0VYSVNUENUI",
          "EiQKH0VSUk9SX0NPREVfVU5JT05fQ0FOTk9UX0FQUE9JTlQQ1ggSIwoeRVJS",
          "T1JfQ09ERV9VTklPTl9DQU5OT1RfUkVNT1ZFENcIEiMKHkVSUk9SX0NPREVf",
          "VU5JT05fQ0FOTk9UX0RFTUlTRRDYCBIjCh5FUlJPUl9DT0RFX1VOSU9OX1FV",
          "SVRfQ09PTERPV04Q2QgSIwoeRVJST1JfQ09ERV9VTklPTl9BUFBMWV9NQVhf",
          "TlVNENoIEiEKHEVSUk9SX0NPREVfVU5JT05fTUVNQkVSX0ZVTEwQ2wgSJQog",
          "RVJST1JfQ09ERV9VTklPTl9KT0lOX1dST05HX0FSRUEQ3AgSIQocRVJST1Jf",
          "Q09ERV9VTklPTl9KT0lOX0ZPUkJJRBDdCBItCihFUlJPUl9DT0RFX1VOSU9O",
          "X1BMQVlFUl9BTFJFQURZX0lOX1VOSU9OEN4IEiwKJ0VSUk9SX0NPREVfVU5J",
          "T05fQ1JFQVRFX01BSU5fQ0lUWV9MSU1JVBDfCBIrCiZFUlJPUl9DT0RFX1VO",
          "SU9OX0NSRUFURV9SRVNfQ09JTl9MSU1JVBDgCBIkCh9FUlJPUl9DT0RFX1VO",
          "SU9OX1RJVExFX05VTV9GVUxMEOEIEiAKG0VSUk9SX0NPREVfVU5JT05fTkVF",
          "RF9BUFBMWRDiCBIhChxFUlJPUl9DT0RFX1VOSU9OX0NBTk5PVF9KT0lOEOMI",
          "EiYKIUVSUk9SX0NPREVfVU5JT05fV1JPTkdfSk9JTl9MSU1JVBDkCBIjCh5F",
          "UlJPUl9DT0RFX1VOSU9OX0NBTk5PVF9ET05BVEUQ5QgSJAofRVJST1JfQ09E",
          "RV9VTklPTl9XUk9OR19SRUxBVElPThDmCBInCiJFUlJPUl9DT0RFX1VOSU9O",
          "X1JFTEFUSU9OX05VTV9GVUxMEOcIEiwKJ0VSUk9SX0NPREVfVU5JT05fUkVM",
          "QVRJT05fQ0FOTk9UX0NIQU5HRRDoCBIjCh5FUlJPUl9DT0RFX1VOSU9OX01B",
          "UktfTlVNX0ZVTEwQ6QgSKQokRVJST1JfQ09ERV9VTklPTl9NQVJLX05BTUVf",
          "TEVOX0xJTUlUEOoIEiwKJ0VSUk9SX0NPREVfVU5JT05fTUFSS19DT05URU50",
          "X0xFTl9MSU1JVBDrCBIjCh5FUlJPUl9DT0RFX1VOSU9OX01BUktfQkFEX1dP",
          "UkQQ7AgSJAofRVJST1JfQ09ERV9VTklPTl9ERVNDX0xFTl9MSU1JVBDtCBIj",
          "Ch5FUlJPUl9DT0RFX1VOSU9OX0RFU0NfQkFEX1dPUkQQ7ggSHwoaRVJST1Jf",
          "Q09ERV9VTklPTl9OT19ERU1JU0UQ7wgSJwoiRVJST1JfQ09ERV9VTklPTl9D",
          "QU5OT1RfU1dBUF9USVRMRRDwCBIlCiBFUlJPUl9DT0RFX1VOSU9OX0NBTk5P",
          "VF9ESVNTT0xWRRDxCBIhChxFUlJPUl9DT0RFX0ZBTExFTl9OT1RfRkFMTEVO",
          "EPQIEiwKJ0VSUk9SX0NPREVfRkFMTEVOX0NBTk5PVF9QQVlfUkVWT0xUX1JF",
          "UxD1CBIiCh1FUlJPUl9DT0RFX0RSSUxMX0lEX05PVF9FWElTVBD+CBIkCh9F",
          "UlJPUl9DT0RFX0RSSUxMX0lEX0lTX05PVF9PUEVOEP8IEigKI0VSUk9SX0NP",
          "REVfRFJJTExfSURfSVNfQUxSRUFEWV9PUEVOEIAJEicKIkVSUk9SX0NPREVf",
          "RFJJTExfTk9fTUVFVF9DT05ESVRJT04QgQkSJgohRVJST1JfQ09ERV9EUklM",
          "TF9DQU5UX0FUVEFDS19USUxFEIIJEiwKJ0VSUk9SX0NPREVfRFJJTExfVElM",
          "RV9JU19BTFJFQURZX09DQ1VQWRCDCRImCiFFUlJPUl9DT0RFX0RSSUxMX0lO",
          "VkFMSURfVElMRV9QT1MQhAkSKAojRVJST1JfQ09ERV9EUklMTF9IRVJPU19X",
          "Uk9OR19OVU1CRVIQhQkSJAofRVJST1JfQ09ERV9EUklMTF9IRVJPX05PVF9F",
          "WElTVBCGCRIqCiVFUlJPUl9DT0RFX0RSSUxMX0hFUk9TX05PVF9SRUFDSF9U",
          "SUxFEIcJEiQKH0VSUk9SX0NPREVfRFJJTExfTk9fRU5PVUdIX0NPSU4QiAkS",
          "HQoYRVJST1JfQ09ERV9EUklMTF9OT19QQVNTEIkJEhsKFkVSUk9SX0NPREVf",
          "RFJJTExfSU5fQ0QQigkSJAofRVJST1JfQ09ERV9EUklMTF9UT09fRElGRklD",
          "VUxUWRCLCRIoCiNFUlJPUl9DT0RFX0RSSUxMX1RVVE9SSUFMX0NBTlRfU0tJ",
          "UBCMCRIrCiZFUlJPUl9DT0RFX0RSSUxMX1RVVE9SSUFMX05PX1NUQVRJU1RJ",
          "QxCNCRIkCh9FUlJPUl9DT0RFX0RSSUxMX0RVUExJQ0FURV9IRVJPEI4JEiAK",
          "G0VSUk9SX0NPREVfQlVJTERfUVVFVUVfRlVMTBCwCRIZChRFUlJPUl9DT0RF",
          "X0xPR0lOX0RBWRCxCRIbChZFUlJPUl9DT0RFX0VSUl9UQVNLX0lEELIJEikK",
          "JEVSUk9SX0NPREVfRVJSX1RBU0tfQUxSRUFEWV9DT01QTEVURRCzCRImCiFF",
          "UlJPUl9DT0RFX0VSUl9UQVNLX0FMUkVBRFlfQVdBUkQQtAkSJAofRVJST1Jf",
          "Q09ERV9FUlJfTE9HSU5fRVZFTlRfTU9SRRC1CRIlCiBFUlJPUl9DT0RFX0VS",
          "Ul9MT0dJTl9FVkVOVF9BV0FSRBC2CRIhChxFUlJPUl9DT0RFX01BSUxfTk9U",
          "X0lOX1VOSU9OELoJEiQKH0VSUk9SX0NPREVfQUxMT0NfTUFQX1BPU19GQUlM",
          "RUQQ0Q8SHgoZRVJST1JfQ09ERV9OT1RfVElMRV9PV05FUhDSDxIfChpFUlJP",
          "Ul9DT0RFX1RJTEVfT05fUFJPVEVDVBDTDxIhChxFUlJPUl9DT0RFX1RJTEVf",
          "SVNfR0lWSU5HX1VQENQPEhsKFkVSUk9SX0NPREVfSU5WQUxJRF9QT1MQ1Q8S",
          "IgodRVJST1JfQ09ERV9USUxFX05PVF9HSVZJTkdfVVAQ1g8SIAobRVJST1Jf",
          "Q09ERV9JTlZBTElEX0dSSURfUE9TENcPEh4KGUVSUk9SX0NPREVfVE9PX01V",
          "Q0hfR1JJRFMQ2A8SIgodRVJST1JfQ09ERV9NQVJDSF9SRVFfVFlQRV9FUlIQ",
          "2Q8SJQogRVJST1JfQ09ERV9BVFRBQ0tfTk9fTkVBUkJZX1RJTEUQ2g8SIgod",
          "RVJST1JfQ09ERV9USUxFX0NBTk5PVF9BVFRBQ0sQ2w8SJQogRVJST1JfQ09E",
          "RV9QTEFZRVJfTk9UX1RJTEVfT1dORVIQ3A8SHAoXRVJST1JfQ09ERV9FUlJf",
          "VFJPT1BfSUQQ3Q8SIwoeRVJST1JfQ09ERV9IRVJPX0lTTk9UX0lOX1RST09Q",
          "EN4PEiMKHkVSUk9SX0NPREVfRklHSFRFUl9OVU1fTElNSVRFRBDfDxIrCiZF",
          "UlJPUl9DT0RFX1RST09QX0NUTF9DT05TQ1JJUFRfRklHSFRFUhDgDxIcChdF",
          "UlJPUl9DT0RFX0VSUl9NQVJDSF9JRBDhDxIlCiBFUlJPUl9DT0RFX1JFVFVS",
          "Tl9NQVJDSF9FUlJfVElNRRDiDxIcChdFUlJPUl9DT0RFX0VSUl9UUk9PUF9O",
          "TxDjDxIfChpFUlJPUl9DT0RFX1RST09QX05PVF9GT1VORBDkDxIfChpFUlJP",
          "Ul9DT0RFX0VSUl9UUk9PUF9TVEFURRDlDxIkCh9FUlJPUl9DT0RFX0ZJR0hU",
          "RVJfU0VSSU9VU19IVVJUEOYPEh8KGkVSUk9SX0NPREVfRVJSX0ZJR0hURVJf",
          "UE9TEOcPEiQKH0VSUk9SX0NPREVfVFJPT1BTX0lOX1RXT19DSVRJRVMQ6A8S",
          "JAofRVJST1JfQ09ERV9GVUxMX0NPTlNDUklQVF9RVUVVRRDpDxIgChtFUlJP",
          "Ul9DT0RFX0hFUk9fRU5FUkdZX0xBQ0sQ6g8SIwoeRVJST1JfQ09ERV9UUk9P",
          "UF9DQU5OT1RfUkVUVVJOEOsPEiQKH0VSUk9SX0NPREVfVFJPT1BfSVNfTk9U",
          "X0lOX0NJVFkQ7A8SHQoYRVJST1JfQ09ERV9UUkFJTl9DTlRfRVJSEO0PEh8K",
          "GkVSUk9SX0NPREVfQ0lUWV9SRURJRl9MQUNLEO4PEisKJkVSUk9SX0NPREVf",
          "UkVESUZfQ09OU0NSSVBUX1JFUV9DTlRfRVJSEO8PEh4KGUVSUk9SX0NPREVf",
          "Q0lUWV9DT1NUX0xBQ0sQ8A8SKAojRVJST1JfQ09ERV9GSUdIVEVSX0hQX01P",
          "UkVfVEhBTl9NQVgQ8Q8SJQogRVJST1JfQ09ERV9DT05TQ1JJUFRfUkVRX0NO",
          "VF9FUlIQ8g8SKAojRVJST1JfQ09ERV9GSUdIVEVSX0lTX05PVF9DT05TQ1JJ",
          "UFQQ8w8SKgolRVJST1JfQ09ERV9SRVRVUk5fVFJPT1BfUkVRX1NUQVRFX0VS",
          "UhD0DxIsCidFUlJPUl9DT0RFX1RST09QU19DT05OT1RfSEFWRV9TQU1FX0hF",
          "Uk8Q9Q8SJwoiRVJST1JfQ09ERV9GSUxURVJfUkFESVVTX1RPT19MQVJHRRD2",
          "DxIlCiBFUlJPUl9DT0RFX1BMQVlFUl9OT1RfQ0lUWV9PV05FUhD3DxIpCiRF",
          "UlJPUl9DT0RFX1RSQU5TRkVSX0NJVFlfVFJPT1BTX0ZVTEwQ+A8SKwomRVJS",
          "T1JfQ09ERV9UUkFOU0ZFUl9QT1NfU0FNRV9UUk9PUF9QT1MQ+Q8SJQogRVJS",
          "T1JfQ09ERV9QT1NfQ09OTk9UX0JVSUxEX0NJVFkQ+g8SKwomRVJST1JfQ09E",
          "RV9DT05OT1RfQlVJTERfVEhJU19DSVRZX1RZUEUQ+w8SHwoaRVJST1JfQ09E",
          "RV9CVUlMRF9DSVRZX0ZVTEwQ/A8SKQokRVJST1JfQ09ERV9USUxFX0VUWVBF",
          "X0lTX05PVF9OT1RISU5HEP0PEioKJUVSUk9SX0NPREVfQ09OTk9UX0RJU01B",
          "TlRMRV9DSVRZX1RZUEUQ/g8SKwomRVJST1JfQ09ERV9DSVRZX1NUQVRFX0NP",
          "Tk5PVF9ESVNNQU5UTEUQ/w8SIAobRVJST1JfQ09ERV9HSVZFVVBfU1BfRU5U",
          "SVRZEIAQEikKJEVSUk9SX0NPREVfRklHSFRFUl9BTFJFQURZX0NPTlNDUklQ",
          "VBCBEBImCiFFUlJPUl9DT0RFX01BUkNIX0NPTlNDUklQVF9GSUdIVEUQghAS",
          "IQocRVJST1JfQ09ERV9PTERfRk9SVFJFU1NfRlVMTBCDEBImCiFFUlJPUl9D",
          "T0RFX09MRF9GT1JUUkVTU19OT1RfRVhJU1QQhBASKAojRVJST1JfQ09ERV9U",
          "Uk9PUF9ORUVEX0ZJUlNUX0ZJR0hURVIQhRASJQogRVJST1JfQ09ERV9DQU5O",
          "T1RfTU9WRV9DSVRZX0hFUkUQhhASJQogRVJST1JfQ09ERV9NT1ZFX0NJVFlf",
          "QlVJTERfUVVFVUUQhxASKQokRVJST1JfQ09ERV9NT1ZFX0NJVFlfQ09OU0NS",
          "SVBUX1FVRVVFEIgQEiAKG0VSUk9SX0NPREVfTU9WRV9DSVRZX0ZBTExFThCJ",
          "EBIjCh5FUlJPUl9DT0RFX01PVkVfQ0lUWV9ESVNNQU5UTEUQihASIgodRVJS",
          "T1JfQ09ERV9DSVRZX0lOX0lOVklOQ0lCTEUQixASJQogRVJST1JfQ09ERV9D",
          "SVRZX0lOVklOQ0lCTEVfU1RBVEUQjBASIQocRVJST1JfQ09ERV9FUElDX0NB",
          "Tk5PVF9BV0FSRBCNEBIoCiNFUlJPUl9DT0RFX0VQSUNfUExBWUVSX0NBTk5P",
          "VF9BV0FSRBCOEBIjCh5FUlJPUl9DT0RFX1BSRVNUSUdFX05PVF9FTk9VR0gQ",
          "jxBiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ERROR_CODE), }, null, null));
  }
  #endregion

}
#region Enums
/// <summary>
/// 通用消息错误码
/// </summary>
public enum ERROR_CODE {
  [pbr::OriginalName("ERROR_CODE_NO_ERROR")] NoError = 0,
  /// <summary>
  /// 通用错误     1-100
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_INTERNAL_ERR")] InternalErr = 1,
  [pbr::OriginalName("ERROR_CODE_PF_ERR")] PfErr = 2,
  [pbr::OriginalName("ERROR_CODE_ERR_SERVER_DATE")] ErrServerDate = 3,
  [pbr::OriginalName("ERROR_CODE_PF_INVALID_ACCESS_TOKEN")] PfInvalidAccessToken = 4,
  [pbr::OriginalName("ERROR_CODE_PERMISSION_VERIFY_FAILED")] PermissionVerifyFailed = 5,
  [pbr::OriginalName("ERROR_CODE_ERR_ILLEGAL_REQ")] ErrIllegalReq = 6,
  /// <summary>
  /// 玩家操作的实体不属于玩家(玩家请求别的玩家的数据进行操作)
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_OP_ET_NOT_BELONG_TO_YOUR")] OpEtNotBelongToYour = 7,
  [pbr::OriginalName("ERROR_CODE_PF_CHARACTER_CREATE_FAILED")] PfCharacterCreateFailed = 8,
  [pbr::OriginalName("ERROR_CODE_PF_LOGIN_FAILED")] PfLoginFailed = 9,
  /// <summary>
  /// 要绑定的账号有角色
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_PF_ACC_LINK_HASCHAR")] PfAccLinkHaschar = 10,
  /// <summary>
  /// 要绑定的账号失败
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_PF_ACC_LINK_FAUKED")] PfAccLinkFauked = 11,
  /// <summary>
  /// 错误的账号类型
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_PF_ACC_INVALIDACCOUNTTYPE")] PfAccInvalidaccounttype = 12,
  /// <summary>
  /// 帐号&amp;登录相关 100 - 1000
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_PLAYER_NOT_FOUND")] PlayerNotFound = 101,
  /// <summary>
  /// 玩家名已存在
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_PLAYER_NAME_ALREADY_EXIST")] PlayerNameAlreadyExist = 102,
  /// <summary>
  /// 玩家名长度限制
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_PLAYER_NAME_LEN_LIMIT")] PlayerNameLenLimit = 103,
  /// <summary>
  /// 玩家名包含敏感词
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_PLAYER_NAME_BAD_WORD")] PlayerNameBadWord = 104,
  /// <summary>
  /// 玩家Auth失败
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_AUTH_FAILED")] AuthFailed = 105,
  /// <summary>
  /// 网关账号创建失败
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ACCOUNT_CREATE_FAILED")] AccountCreateFailed = 106,
  /// <summary>
  /// 网关上玩家不存在
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_PLAYER_NOT_FOUND_2")] PlayerNotFound2 = 107,
  /// <summary>
  /// 网关上账号不存在
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ACCOUNT_NOT_FOUND")] AccountNotFound = 108,
  /// <summary>
  /// 网关上增加玩家失败
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_GATE_ADD_ROLE_FAILED")] GateAddRoleFailed = 109,
  /// <summary>
  /// 设备UDID错误
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_INVALID_DEVICE")] InvalidDevice = 110,
  /// <summary>
  /// 只能绑定匿名账号
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_CANOT_BIND")] CanotBind = 111,
  /// <summary>
  /// 该服务器已存在角色
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_DUPLICATE_CREATE_PLAYER")] DuplicateCreatePlayer = 112,
  /// <summary>
  /// 多点登录，等待已有角色登出超时
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_LOGIN_WAIT_LOGOUT_TIMEOUT")] LoginWaitLogoutTimeout = 113,
  /// <summary>
  /// 多点登录， 已有登录状态错误
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_LOGIN_WITH_ERR_STATE")] LoginWithErrState = 114,
  /// <summary>
  /// clientinfo 为空
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_NILCLIENTINFO")] Nilclientinfo = 115,
  /// <summary>
  /// 目标服务器没找到
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_SERVER_NOT_FOUND")] ServerNotFound = 116,
  /// <summary>
  /// 连接目标服务器失败
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_CONNECT_SERVER_FAILED")] ConnectServerFailed = 117,
  /// <summary>
  /// 多次登陆
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_DUPLICATE_LOGIN")] DuplicateLogin = 118,
  /// <summary>
  /// FastLoginSecret错误
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_FASTLOGINSECRETERR")] Fastloginsecreterr = 119,
  /// <summary>
  /// 被禁止消息
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_FORBIDEDMSG")] Forbidedmsg = 120,
  /// <summary>
  /// 名字无改变
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_PLAYERNAME_NOCHANG")] PlayernameNochang = 121,
  /// <summary>
  /// 名字无改变
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_PLAYER_NAME_LEN_SHORT")] PlayerNameLenShort = 122,
  /// <summary>
  /// play相关 1000 - 2000 city/hero/skill/breport/land
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_CITY_ID")] ErrCityId = 1001,
  /// <summary>
  /// 没有找到英雄
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_HERO_RID")] ErrHeroRid = 1002,
  /// <summary>
  /// 英雄在其他队伍中
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_HERO_IS_IN_OTHER_TROOP")] HeroIsInOtherTroop = 1003,
  /// <summary>
  /// 玩家资源不够
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_PLAYER_RES_LACK")] PlayerResLack = 1004,
  /// <summary>
  /// 没有找到建筑
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_BUILD_ID")] ErrBuildId = 1005,
  /// <summary>
  /// 城建已经达到满级
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_BUILD_ALREADY_MAX_LEVEL")] BuildAlreadyMaxLevel = 1006,
  /// <summary>
  /// 需要升级其他依赖建筑
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_BUILD_RELY_ON")] ErrBuildRelyOn = 1007,
  /// <summary>
  /// 建筑已经升级
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_BUILD_ALREADY_UPGRADE")] BuildAlreadyUpgrade = 1008,
  /// <summary>
  /// 战报已拉取
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_BREPORT_ALREADY_COLLECT")] BreportAlreadyCollect = 1009,
  /// <summary>
  /// 拉取战报数量已达最大
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_FULL_COLLECT_BREPORT")] FullCollectBreport = 1010,
  /// <summary>
  /// 技能已经被研究
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_SKILL_ALREADY_RESEARCH")] SkillAlreadyResearch = 1012,
  /// <summary>
  /// 技能研究完成
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_SKILL_IS_INTEGRITY")] SkillIsIntegrity = 1013,
  /// <summary>
  /// 第一个技能英雄等级不够，第一个技能英雄没有觉醒
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_HERO_CANNOT_LEARN_SKILL")] HeroCannotLearnSkill = 1014,
  /// <summary>
  /// 英雄没有学习技能, 因此不能遗忘
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_HERO_CANNOT_FORGET_SKILL")] HeroCannotForgetSkill = 1015,
  /// <summary>
  /// 没有找到战报
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_BREPORT_ID")] ErrBreportId = 1016,
  /// <summary>
  /// 英雄缺少足够的可分配属性点
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_HERO_REMAIN_ASGN_LACK")] ErrHeroRemainAsgnLack = 1017,
  /// <summary>
  /// 英雄红星已经满了，无法进阶
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_HERO_ALREADY_MAX_ADVSTAR")] HeroAlreadyMaxAdvstar = 1018,
  /// <summary>
  /// 指定的消耗英雄无法删除 (学习了技能,锁定, 在队伍中)
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_CONSUME_HERO_CANNOT_DEL")] ConsumeHeroCannotDel = 1019,
  /// <summary>
  /// 进阶消耗的英雄与进阶英雄hero_id的不同
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_PROMOTE_CONSUME_HERO_NOT_SAME")] PromoteConsumeHeroNotSame = 1020,
  /// <summary>
  /// 英雄已经觉醒
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_HERO_HAS_AWAKE")] HeroHasAwake = 1022,
  /// <summary>
  /// 玩家已完成新手教学
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_PLAYER_ALREADY_FINISH_NEWBIE")] PlayerAlreadyFinishNewbie = 1024,
  /// <summary>
  /// 觉醒英雄和消耗英雄星级不一样
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_AWAKE_CONSUME_STAR_NOT_SAME")] AwakeConsumeStarNotSame = 1025,
  /// <summary>
  /// 被消耗的英雄在队伍中
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_CONSUME_HERO_IN_TROOP")] ConsumeHeroInTroop = 1026,
  /// <summary>
  /// 觉醒英雄消耗个数错误（小于2）
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_HREO_AWAKE_CONSUME_CNT_ERR")] HreoAwakeConsumeCntErr = 1027,
  /// <summary>
  /// 英雄技能索引不在 0-2 之间
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_SKILL_INDEX_OUT_OF_RANGE")] SkillIndexOutOfRange = 1029,
  /// <summary>
  /// 技能不能被学习(研究进度小于100，已经超过最大学习次数)
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_SKILL_CANNOT_BE_LEARNED")] SkillCannotBeLearned = 1030,
  /// <summary>
  /// 英雄index位置已经学习了技能
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_INDEX_ALREADY_LEARN_SKILL")] IndexAlreadyLearnSkill = 1031,
  /// <summary>
  /// 发送的id里面有重复
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_REPEAT_ID")] RepeatId = 1032,
  /// <summary>
  /// 英雄已经学习了该技能,不能再次该学习
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_HERO_ALREADY_LEARN_THIS_SKILL")] HeroAlreadyLearnThisSkill = 1033,
  /// <summary>
  /// 没有找到此技能
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_SKILL_ID")] ErrSkillId = 1034,
  /// <summary>
  /// 英雄兵种与技能可学习兵种不符
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_HERO_KIND_NOT_MATCH_SKILL")] HeroKindNotMatchSkill = 1035,
  /// <summary>
  /// 英雄不能研究这个技能 (英雄兵种, 星级不符)
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_HERO_CONNOT_RESEARCH_THIS_SKILL")] HeroConnotResearchThisSkill = 1036,
  /// <summary>
  /// 技能等级不一致(在学习技能时为了避免数据不一致,需要与客户端验证技能等级)
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_SKILL_LEVEL")] ErrSkillLevel = 1037,
  /// <summary>
  /// 战法经验不足
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_SKILL_EXP_LACK")] ErrSkillExpLack = 1038,
  /// <summary>
  /// 英雄已锁定
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_HERO_ALREADY_LOCKED")] HeroAlreadyLocked = 1039,
  /// <summary>
  /// 英雄已解锁
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_HERO_ALREADY_UNLOCKED")] HeroAlreadyUnlocked = 1040,
  /// <summary>
  /// 属性分配的值错误（小于0或者比原来的值小）
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ALLOT_ASGN_VALUE_ERR")] AllotAsgnValueErr = 1041,
  /// <summary>
  /// 英雄等级不能觉醒
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_HERO_LEVEL_CANNOT_AWAKE")] HeroLevelCannotAwake = 1042,
  /// <summary>
  /// 英雄自带技能等级不能觉醒
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_FIRST_SKILL_LEVEL_CANNOT_AWAKE")] FirstSkillLevelCannotAwake = 1043,
  /// <summary>
  /// 玩家钻石不足
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_PLAYER_DIAMOND_LACK")] PlayerDiamondLack = 1044,
  /// <summary>
  /// is_free 字段不一致
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_RESET_ASGN_TYPE_NOT_MATCH")] ResetAsgnTypeNotMatch = 1045,
  /// <summary>
  /// 建筑没有在升级
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_BUILD_IS_NOT_UPGRADE")] BuildIsNotUpgrade = 1046,
  /// <summary>
  /// 收税次数已达上限
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_COLLECT_TAXES_CNT_MAX")] CollectTaxesCntMax = 1047,
  /// <summary>
  /// 资源交易目标与源资源一样
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_TRANS_RES_SRC_DEST_SAME")] TransResSrcDestSame = 1048,
  /// <summary>
  /// 资源交易小于0
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_TRANS_RES_CNT_LESS_THAN_0")] TransResCntLessThan0 = 1049,
  /// <summary>
  /// 玩家没有建筑交易所,不能交易
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_PLAYER_HAVE_NOT_TRANS_BUILD")] PlayerHaveNotTransBuild = 1050,
  /// <summary>
  /// src/dest 不能交易
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_TRANS_RES_SRC_DEST_ERR")] TransResSrcDestErr = 1051,
  /// <summary>
  /// 玩家收藏土地已满
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_FULL_COLLECT_LANDS")] FullCollectLands = 1052,
  /// <summary>
  /// 玩家金币不足
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_PLAYER_COIN_LACK")] ErrPlayerCoinLack = 1053,
  /// <summary>
  /// 玩家英雄上限
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_PLAYER_HERO_FULL")] PlayerHeroFull = 1054,
  /// <summary>
  /// 玩家技能上限
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_PLAYER_SKILL_FULL")] PlayerSkillFull = 1055,
  /// <summary>
  /// 任务不处于可领奖状态
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_NOT_COMPLEATED_TASK")] NotCompleatedTask = 1056,
  /// <summary>
  /// 不合法的任务id
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_TASKID")] ErrTaskid = 1057,
  /// <summary>
  /// 任务不存在
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_TASK_NOT_EXIST")] TaskNotExist = 1058,
  /// <summary>
  /// 后续任务ID不合法
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_NEXT_TASKID")] ErrNextTaskid = 1059,
  /// <summary>
  /// 未知的任务奖励名称
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNKNOWN_TASK_PRIZE")] UnknownTaskPrize = 1060,
  /// <summary>
  /// 没有找到商品 如商品id错误 商品已经出售
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_NO_GOODS_NAME")] NoGoodsName = 1061,
  /// <summary>
  /// 购买商品时 缺少商品所需要的资源
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_LACK_RESOURCE")] LackResource = 1062,
  /// <summary>
  /// 无效的购买请求
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_INVALID_PURCHASE")] InvalidPurchase = 1063,
  /// <summary>
  /// 市场ID错误
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_WRONG_MARKET_ID")] WrongMarketId = 1064,
  /// <summary>
  /// 市场未解锁
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_MARKET_LOCKED")] MarketLocked = 1065,
  /// <summary>
  ///未满足收税时间间隔
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_TAX_TIME_INTERVAL")] TaxTimeInterval = 1066,
  /// <summary>
  /// 已经卖出
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_GOODS_SOLD_OUT")] GoodsSoldOut = 1067,
  /// <summary>
  /// 交易 资源兑换率为0 没有启用交易功能时
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_TRADE_ZERO_RATE")] TradeZeroRate = 1068,
  /// <summary>
  /// 无效的资源 数量非正 id错误
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_INVALID_RES")] InvalidRes = 1069,
  /// <summary>
  /// 同种资源无法交易
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_SAME_RES")] SameRes = 1070,
  /// <summary>
  /// 超过商店最大刷新次数
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_MAX_MARKET_REFRESH_TIMES")] MaxMarketRefreshTimes = 1071,
  /// <summary>
  /// 升级建筑物所需的地块等级不够
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_BUILD_TILE_LEVEL_LIMIT")] BuildTileLevelLimit = 1072,
  /// <summary>
  /// 进阶消耗英雄为0
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_PROMOTE_CONSUME_HERO_CNT_ERR")] PromoteConsumeHeroCntErr = 1073,
  /// <summary>
  /// 人民币玩家收税次数已达上限
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_FORCE_COLLECT_TAXES_CNT_MAX")] ForceCollectTaxesCntMax = 1074,
  /// <summary>
  /// 人民币玩家不需要强征，已经到第二天了
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_NOT_REQUIRE_FORCE_COLLECT")] NotRequireForceCollect = 1075,
  /// <summary>
  /// 政令不足
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ORDER_LACK")] OrderLack = 1076,
  /// <summary>
  /// 头像的index错误
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_AVATAR_WRONG_INDEX")] AvatarWrongIndex = 1077,
  /// <summary>
  /// 简介长度错误
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_INTRO_WRONG_LENGTH")] IntroWrongLength = 1078,
  /// <summary>
  /// 简介带有敏感词
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_INTRO_BAD_WORD")] IntroBadWord = 1079,
  /// <summary>
  /// push event错误, 服务器没有定义
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_PUSH_EVENT")] ErrPushEvent = 1080,
  /// <summary>
  ///gacha
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_GACHA_ERR_PACKAGEID")] ErrGachaErrPackageid = 1081,
  /// <summary>
  /// push event错误, 服务器没有定义
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_GACHA_END")] ErrGachaEnd = 1095,
  /// <summary>
  /// 客户端商店数据为过期
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_MARKET_OLD_DATA")] MarketOldData = 1096,
  /// <summary>
  /// 联盟相关
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_OP_NO_AUTHORITY")] UnionOpNoAuthority = 1100,
  /// <summary>
  /// 联盟名已存在
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_NAME_ALREADY_EXIST")] UnionNameAlreadyExist = 1101,
  /// <summary>
  /// 联盟名长度限制
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_NAME_LEN_LIMIT")] UnionNameLenLimit = 1102,
  /// <summary>
  /// 联盟名包含敏感词
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_NAME_BAD_WORD")] UnionNameBadWord = 1103,
  /// <summary>
  /// 联盟不存在
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_NOT_EXIST")] UnionNotExist = 1104,
  /// <summary>
  /// 玩家已经申请该联盟
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_ALREADY_APPLY")] UnionAlreadyApply = 1105,
  /// <summary>
  /// 玩家没有申请该联盟
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_NOT_APPLY")] UnionNotApply = 1107,
  /// <summary>
  /// 玩家不在该联盟
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_MEMBER_NOT_EXIST")] UnionMemberNotExist = 1108,
  /// <summary>
  /// 该职位不存在
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_TITLE_NOT_EXIST")] UnionTitleNotExist = 1109,
  /// <summary>
  /// 不能任命该成员
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_CANNOT_APPOINT")] UnionCannotAppoint = 1110,
  /// <summary>
  /// 不能移除该成员
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_CANNOT_REMOVE")] UnionCannotRemove = 1111,
  /// <summary>
  /// 不能禅让给该成员
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_CANNOT_DEMISE")] UnionCannotDemise = 1112,
  /// <summary>
  /// 玩家在退盟冷却中
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_QUIT_COOLDOWN")] UnionQuitCooldown = 1113,
  /// <summary>
  /// 已达最大联盟申请数量
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_APPLY_MAX_NUM")] UnionApplyMaxNum = 1114,
  /// <summary>
  /// 联盟成员已满
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_MEMBER_FULL")] UnionMemberFull = 1115,
  /// <summary>
  /// 不能申请或加入其他区域的联盟
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_JOIN_WRONG_AREA")] UnionJoinWrongArea = 1116,
  /// <summary>
  /// 联盟申请或加入条件：禁止加入
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_JOIN_FORBID")] UnionJoinForbid = 1117,
  /// <summary>
  /// 玩家已经加入了联盟
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_PLAYER_ALREADY_IN_UNION")] UnionPlayerAlreadyInUnion = 1118,
  /// <summary>
  /// 创建联盟时城主府等级不足
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_CREATE_MAIN_CITY_LIMIT")] UnionCreateMainCityLimit = 1119,
  /// <summary>
  /// 创建联盟时金币不足
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_CREATE_RES_COIN_LIMIT")] UnionCreateResCoinLimit = 1120,
  /// <summary>
  /// 联盟该职位已满
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_TITLE_NUM_FULL")] UnionTitleNumFull = 1121,
  /// <summary>
  /// 需要申请加入
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_NEED_APPLY")] UnionNeedApply = 1122,
  /// <summary>
  /// 不能直接加入
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_CANNOT_JOIN")] UnionCannotJoin = 1123,
  /// <summary>
  /// 设置了错误的联盟加入条件
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_WRONG_JOIN_LIMIT")] UnionWrongJoinLimit = 1124,
  /// <summary>
  /// 不能捐献
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_CANNOT_DONATE")] UnionCannotDonate = 1125,
  /// <summary>
  /// 设置了错误的联盟关系
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_WRONG_RELATION")] UnionWrongRelation = 1126,
  /// <summary>
  /// 联盟外交关系已达上限
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_RELATION_NUM_FULL")] UnionRelationNumFull = 1127,
  /// <summary>
  /// 联盟外交关系不能改变
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_RELATION_CANNOT_CHANGE")] UnionRelationCannotChange = 1128,
  /// <summary>
  /// 联盟标记数量已达上限
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_MARK_NUM_FULL")] UnionMarkNumFull = 1129,
  /// <summary>
  /// 联盟标记名长度限制
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_MARK_NAME_LEN_LIMIT")] UnionMarkNameLenLimit = 1130,
  /// <summary>
  /// 联盟标记内容长度限制
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_MARK_CONTENt_LEN_LIMIT")] UnionMarkContentLenLimit = 1131,
  /// <summary>
  /// 联盟标记包含敏感词
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_MARK_BAD_WORD")] UnionMarkBadWord = 1132,
  /// <summary>
  /// 联盟描述长度限制
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_DESC_LEN_LIMIT")] UnionDescLenLimit = 1133,
  /// <summary>
  /// 联盟描述包含敏感词
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_DESC_BAD_WORD")] UnionDescBadWord = 1134,
  /// <summary>
  /// 没有发起禅让
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_NO_DEMISE")] UnionNoDemise = 1135,
  /// <summary>
  /// 不能交换两个官员的职位
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_CANNOT_SWAP_TITLE")] UnionCannotSwapTitle = 1136,
  /// <summary>
  /// 不能解散联盟
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_UNION_CANNOT_DISSOLVE")] UnionCannotDissolve = 1137,
  /// <summary>
  /// 沦陷相关
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_FALLEN_NOT_FALLEN")] FallenNotFallen = 1140,
  /// <summary>
  /// 不能上缴反叛资源
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_FALLEN_CANNOT_PAY_REVOLT_RES")] FallenCannotPayRevoltRes = 1141,
  /// <summary>
  /// 演武 1150 ~ 1200
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_DRILL_ID_NOT_EXIST")] DrillIdNotExist = 1150,
  /// <summary>
  /// 关卡没有开启
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_DRILL_ID_IS_NOT_OPEN")] DrillIdIsNotOpen = 1151,
  /// <summary>
  /// 关卡已经打开
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_DRILL_ID_IS_ALREADY_OPEN")] DrillIdIsAlreadyOpen = 1152,
  /// <summary>
  /// 关卡不能打开（前置条件不满足）
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_DRILL_NO_MEET_CONDITION")] DrillNoMeetCondition = 1153,
  /// <summary>
  /// 不能攻击关卡土地（没有连接地）
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_DRILL_CANT_ATTACK_TILE")] DrillCantAttackTile = 1154,
  /// <summary>
  /// 土地已经被占领
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_DRILL_TILE_IS_ALREADY_OCCUPY")] DrillTileIsAlreadyOccupy = 1155,
  /// <summary>
  /// 土地位置错误
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_DRILL_INVALID_TILE_POS")] DrillInvalidTilePos = 1156,
  /// <summary>
  /// 攻击部队英雄数量错误
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_DRILL_HEROS_WRONG_NUMBER")] DrillHerosWrongNumber = 1157,
  /// <summary>
  /// 攻击部队英雄不存在
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_DRILL_HERO_NOT_EXIST")] DrillHeroNotExist = 1158,
  /// <summary>
  /// 攻击部队配置不满足土地要求（英雄数量，Cost）
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_DRILL_HEROS_NOT_REACH_TILE")] DrillHerosNotReachTile = 1159,
  /// <summary>
  /// 金币不够
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_DRILL_NO_ENOUGH_COIN")] DrillNoEnoughCoin = 1160,
  /// <summary>
  /// 当前关卡每通过，不能开启下一关（教学演武有效）
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_DRILL_NO_PASS")] DrillNoPass = 1161,
  /// <summary>
  /// 关卡处于冷却期，不能开启下一关
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_DRILL_IN_CD")] DrillInCd = 1162,
  /// <summary>
  /// 前一难度没有通关，不能开启当前难度关卡
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_DRILL_TOO_DIFFICULTY")] DrillTooDifficulty = 1163,
  /// <summary>
  /// 教学演武不能跳过动画学演武有效）    
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_DRILL_TUTORIAL_CANT_SKIP")] DrillTutorialCantSkip = 1164,
  /// <summary>
  /// 教学演武没有统计数据
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_DRILL_TUTORIAL_NO_STATISTIC")] DrillTutorialNoStatistic = 1165,
  /// <summary>
  /// 演武攻击部队，武将重复
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_DRILL_DUPLICATE_HERO")] DrillDuplicateHero = 1166,
  /// <summary>
  /// 建造队列已满
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_BUILD_QUEUE_FULL")] BuildQueueFull = 1200,
  /// <summary>
  /// 登录天数奖励
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_LOGIN_DAY")] LoginDay = 1201,
  /// <summary>
  /// 任务ID错误
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_TASK_ID")] ErrTaskId = 1202,
  /// <summary>
  /// 任务已经完成
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_TASK_ALREADY_COMPLETE")] ErrTaskAlreadyComplete = 1203,
  /// <summary>
  /// 任务已经领奖
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_TASK_ALREADY_AWARD")] ErrTaskAlreadyAward = 1204,
  /// <summary>
  /// 登录超过30天
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_LOGIN_EVENT_MORE")] ErrLoginEventMore = 1205,
  /// <summary>
  /// 当天奖励已领取
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_LOGIN_EVENT_AWARD")] ErrLoginEventAward = 1206,
  /// <summary>
  /// 邮件 1210 - 1219
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_MAIL_NOT_IN_UNION")] MailNotInUnion = 1210,
  /// <summary>
  /// map相关 2000 - 3000 troop/march/fighter/tile
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ALLOC_MAP_POS_FAILED")] AllocMapPosFailed = 2001,
  /// <summary>
  /// 玩家不是土地所有者
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_NOT_TILE_OWNER")] NotTileOwner = 2002,
  /// <summary>
  /// 土地在占免期
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_TILE_ON_PROTECT")] TileOnProtect = 2003,
  /// <summary>
  /// 土地在放弃过程中
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_TILE_IS_GIVING_UP")] TileIsGivingUp = 2004,
  /// <summary>
  /// 土地位置错误
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_INVALID_POS")] InvalidPos = 2005,
  /// <summary>
  /// 土地不在放弃过程中
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_TILE_NOT_GIVING_UP")] TileNotGivingUp = 2006,
  /// <summary>
  /// 土地所在格子位置错误
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_INVALID_GRID_POS")] InvalidGridPos = 2007,
  /// <summary>
  /// 拉取土地的格子过多
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_TOO_MUCH_GRIDS")] TooMuchGrids = 2008,
  /// <summary>
  /// 行军请求类型错误
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_MARCH_REQ_TYPE_ERR")] MarchReqTypeErr = 2009,
  /// <summary>
  /// 出征没有连通地块
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ATTACK_NO_NEARBY_TILE")] AttackNoNearbyTile = 2010,
  /// <summary>
  /// 地块不能被攻击
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_TILE_CANNOT_ATTACK")] TileCannotAttack = 2011,
  /// <summary>
  /// 玩家不是地块所有者
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_PLAYER_NOT_TILE_OWNER")] PlayerNotTileOwner = 2012,
  /// <summary>
  /// 没有此ID队伍
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_TROOP_ID")] ErrTroopId = 2013,
  /// <summary>
  /// 英雄不在部队中
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_HERO_ISNOT_IN_TROOP")] HeroIsnotInTroop = 2014,
  /// <summary>
  /// 队伍中英雄数量达到上限
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_FIGHTER_NUM_LIMITED")] FighterNumLimited = 2015,
  /// <summary>
  /// 部队配置正在征兵的fighter
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_TROOP_CTL_CONSCRIPT_FIGHTER")] TroopCtlConscriptFighter = 2016,
  /// <summary>
  /// 没有找到此ID的行军
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_MARCH_ID")] ErrMarchId = 2017,
  /// <summary>
  /// 已超过可撤回时间
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_RETURN_MARCH_ERR_TIME")] ReturnMarchErrTime = 2018,
  /// <summary>
  /// 部队数量错误
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_TROOP_NO")] ErrTroopNo = 2019,
  /// <summary>
  /// 部队没有找到
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_TROOP_NOT_FOUND")] TroopNotFound = 2020,
  /// <summary>
  /// 部队状态错误
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_TROOP_STATE")] ErrTroopState = 2021,
  /// <summary>
  /// 部队成员重伤
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_FIGHTER_SERIOUS_HURT")] FighterSeriousHurt = 2022,
  /// <summary>
  /// 部队成员位置错误
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_ERR_FIGHTER_POS")] ErrFighterPos = 2023,
  /// <summary>
  /// 2支部队不在同一城中
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_TROOPS_IN_TWO_CITIES")] TroopsInTwoCities = 2024,
  /// <summary>
  /// 征兵队列已满
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_FULL_CONSCRIPT_QUEUE")] FullConscriptQueue = 2025,
  /// <summary>
  /// 体力不足
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_HERO_ENERGY_LACK")] HeroEnergyLack = 2026,
  /// <summary>
  /// 部队无法撤退
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_TROOP_CANNOT_RETURN")] TroopCannotReturn = 2027,
  /// <summary>
  /// 部队不在城中
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_TROOP_IS_NOT_IN_CITY")] TroopIsNotInCity = 2028,
  /// <summary>
  /// 练兵次数
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_TRAIN_CNT_ERR")] TrainCntErr = 2029,
  /// <summary>
  /// 预备兵不足
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_CITY_REDIF_LACK")] CityRedifLack = 2030,
  /// <summary>
  /// cnt &lt;= 0
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_REDIF_CONSCRIPT_REQ_CNT_ERR")] RedifConscriptReqCntErr = 2031,
  /// <summary>
  /// 城池cost不足
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_CITY_COST_LACK")] CityCostLack = 2032,
  /// <summary>
  /// 征兵数量超过部队上限
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_FIGHTER_HP_MORE_THAN_MAX")] FighterHpMoreThanMax = 2033,
  /// <summary>
  /// normal &lt; 0 || redif &lt; 0
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_CONSCRIPT_REQ_CNT_ERR")] ConscriptReqCntErr = 2034,
  /// <summary>
  /// 英雄没有在征兵
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_FIGHTER_IS_NOT_CONSCRIPT")] FighterIsNotConscript = 2035,
  /// <summary>
  /// 返回部队请求部队转态与部队不一致
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_RETURN_TROOP_REQ_STATE_ERR")] ReturnTroopReqStateErr = 2036,
  /// <summary>
  /// 所有部队不能上阵相同的英雄
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_TROOPS_CONNOT_HAVE_SAME_HERO")] TroopsConnotHaveSameHero = 2037,
  /// <summary>
  /// 筛选土地半径过大
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_FILTER_RADIUS_TOO_LARGE")] FilterRadiusTooLarge = 2038,
  /// <summary>
  /// 玩家不是城池的所有者
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_PLAYER_NOT_CITY_OWNER")] PlayerNotCityOwner = 2039,
  /// <summary>
  /// 调动指定的城市队伍已满
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_TRANSFER_CITY_TROOPS_FULL")] TransferCityTroopsFull = 2040,
  /// <summary>
  /// 调动指定的位置与部队现在的位置一致
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_TRANSFER_POS_SAME_TROOP_POS")] TransferPosSameTroopPos = 2041,
  /// <summary>
  /// 指定位置不能修建城池
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_POS_CONNOT_BUILD_CITY")] PosConnotBuildCity = 2042,
  /// <summary>
  /// 指定的城池类型不能修建
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_CONNOT_BUILD_THIS_CITY_TYPE")] ConnotBuildThisCityType = 2043,
  /// <summary>
  /// 指定修建的城池以满
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_BUILD_CITY_FULL")] BuildCityFull = 2044,
  /// <summary>
  /// 屯田,练兵,扫荡指定的土地上面有建筑
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_TILE_ETYPE_IS_NOT_NOTHING")] TileEtypeIsNotNothing = 2045,
  /// <summary>
  /// 不能拆除的建筑类型
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_CONNOT_DISMANTLE_CITY_TYPE")] ConnotDismantleCityType = 2046,
  /// <summary>
  /// 建筑状态不能别拆除
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_CITY_STATE_CONNOT_DISMANTLE")] CityStateConnotDismantle = 2047,
  /// <summary>
  /// 放弃土地上拥有特殊的实体, 主城, 分城, 自己的城区
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_GIVEUP_SP_ENTITY")] GiveupSpEntity = 2048,
  /// <summary>
  /// 英雄正在征兵，不能再次征兵
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_FIGHTER_ALREADY_CONSCRIPT")] FighterAlreadyConscript = 2049,
  /// <summary>
  /// 英雄在征兵, 不能出征
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_MARCH_CONSCRIPT_FIGHTE")] MarchConscriptFighte = 2050,
  /// <summary>
  /// 部队从要塞1调动到要塞2, 想撤退, 但是要塞1已经满了
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_OLD_FORTRESS_FULL")] OldFortressFull = 2051,
  /// <summary>
  /// 部队从要塞1调动到要塞2, 想撤退, 但是要塞1不存在
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_OLD_FORTRESS_NOT_EXIST")] OldFortressNotExist = 2052,
  /// <summary>
  /// 部队必须配置大营才可出征
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_TROOP_NEED_FIRST_FIGHTER")] TroopNeedFirstFighter = 2053,
  /// <summary>
  /// 不能迁城到此地
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_CANNOT_MOVE_CITY_HERE")] CannotMoveCityHere = 2054,
  /// <summary>
  /// 有正在升级的建筑
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_MOVE_CITY_BUILD_QUEUE")] MoveCityBuildQueue = 2055,
  /// <summary>
  /// 有正在征兵的队伍
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_MOVE_CITY_CONSCRIPT_QUEUE")] MoveCityConscriptQueue = 2056,
  /// <summary>
  /// 被沦陷
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_MOVE_CITY_FALLEN")] MoveCityFallen = 2057,
  /// <summary>
  /// 处于拆除中
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_MOVE_CITY_DISMANTLE")] MoveCityDismantle = 2058,
  /// <summary>
  /// 坚守中
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_CITY_IN_INVINCIBLE")] CityInInvincible = 2059,
  /// <summary>
  /// 状态不是normal，不能坚守
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_CITY_INVINCIBLE_STATE")] CityInvincibleState = 2060,
  /// <summary>
  /// 天下大势不能领奖
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_EPIC_CANNOT_AWARD")] EpicCannotAward = 2061,
  /// <summary>
  /// 玩家天下大势不能领奖
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_EPIC_PLAYER_CANNOT_AWARD")] EpicPlayerCannotAward = 2062,
  /// <summary>
  /// 声望不足
  /// </summary>
  [pbr::OriginalName("ERROR_CODE_PRESTIGE_NOT_ENOUGH")] PrestigeNotEnough = 2063,
}

#endregion


#endregion Designer generated code
